<?php
/* @var $this PseudocodeController */

$this->breadcrumbs=array(
	'Pseudocode'=>array('/sql/pseudocode'),
	'Introduction',
);
?>

<h2>What is SQL Pseudocode?</h2>
<p>When a user enters a SQL command, the database has to translate the command into something it can understand and process. The code generated by the database that it actually uses to process the user's command is called <strong>pseudocode.</strong></p>
